In [40]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# =========================================================
# LOAD CSV DATA
# =========================================================

baca = pd.read_csv("baca_results.csv")
aca = pd.read_csv("aca_results.csv")

# =========================================================
# CREATE INTERACTIVE FIGURE
# =========================================================

fig = go.Figure()

# =========================================================
# BACA CURVES
# =========================================================

d_values = sorted(baca["d"].unique())

for d in d_values:

    df = baca[baca["d"] == d]
    df = df.sort_values("n")

    x = df["n"].to_numpy()

    elapsed = df["elapsed"].to_numpy()
    rank = df["rank"].to_numpy()

    y = elapsed / rank

    # -----------------------------------------------------
    # MEASURED DATA
    # -----------------------------------------------------

    fig.add_trace(
        go.Scatter(
            x=x,
            y=y,
            mode='markers',
            name=f'BACA d={d} measured'
        )
    )

    # -----------------------------------------------------
    # LINEAR FIT
    # -----------------------------------------------------

    coeff_lin = np.polyfit(x, y, 1)
    fit_lin = np.poly1d(coeff_lin)

    x_fit = np.linspace(
        np.min(x),
        np.max(x),
        300
    )

    fig.add_trace(
        go.Scatter(
            x=x_fit,
            y=fit_lin(x_fit),
            mode='lines',
            name=f'BACA d={d} linear fit'
        )
    )

    # -----------------------------------------------------
    # QUADRATIC FIT
    # -----------------------------------------------------

    coeff_quad = np.polyfit(x, y, 2)
    fit_quad = np.poly1d(coeff_quad)

    fig.add_trace(
        go.Scatter(
            x=x_fit,
            y=fit_quad(x_fit),
            mode='lines',
            name=f'BACA d={d} quadratic fit',
            visible='legendonly'  # hidden initially
        )
    )

    # -----------------------------------------------------
    # PRINT COEFFICIENTS
    # -----------------------------------------------------

    print("\n===================================")
    print(f"BACA d = {d}")
    print("===================================")

    print("Linear coefficients:")
    print(coeff_lin)

    print("\nQuadratic coefficients:")
    print(coeff_quad)

# =========================================================
# ACA DATA
# =========================================================

aca = aca.sort_values("n")

x_aca = aca["n"].to_numpy()

elapsed_aca = aca["elapsed"].to_numpy()
rank_aca = aca["rank"].to_numpy()

y_aca = elapsed_aca / rank_aca

# ---------------------------------------------------------
# ACA MEASURED
# ---------------------------------------------------------

fig.add_trace(
    go.Scatter(
        x=x_aca,
        y=y_aca,
        mode='markers',
        name='ACA measured'
    )
)

# ---------------------------------------------------------
# ACA LINEAR FIT
# ---------------------------------------------------------

coeff_lin_aca = np.polyfit(x_aca, y_aca, 1)
fit_lin_aca = np.poly1d(coeff_lin_aca)

x_fit_aca = np.linspace(
    np.min(x_aca),
    np.max(x_aca),
    300
)

fig.add_trace(
    go.Scatter(
        x=x_fit_aca,
        y=fit_lin_aca(x_fit_aca),
        mode='lines',
        name='ACA linear fit'
    )
)

# ---------------------------------------------------------
# ACA QUADRATIC FIT
# ---------------------------------------------------------

coeff_quad_aca = np.polyfit(x_aca, y_aca, 2)
fit_quad_aca = np.poly1d(coeff_quad_aca)

fig.add_trace(
    go.Scatter(
        x=x_fit_aca,
        y=fit_quad_aca(x_fit_aca),
        mode='lines',
        name='ACA quadratic fit',
        visible='legendonly'
    )
)

# =========================================================
# PRINT ACA COEFFICIENTS
# =========================================================

print("\n===================================")
print("ACA")
print("===================================")

print("Linear coefficients:")
print(coeff_lin_aca)

print("\nQuadratic coefficients:")
print(coeff_quad_aca)

# =========================================================
# LAYOUT
# =========================================================

fig.update_layout(
    title="ACA vs BACA Runtime Scaling",
    xaxis_title="n",
    yaxis_title="elapsed / rank",
    template="plotly_white",
    hovermode="x unified",
    width=1200,
    height=700
)

# =========================================================
# SHOW
# =========================================================

fig.show()


BACA d = 2
Linear coefficients:
[1.72181608e-05 2.56800154e-02]

Quadratic coefficients:
[-6.45771592e-08  3.14273093e-04 -2.82353034e-01]

BACA d = 4
Linear coefficients:
[ 4.69755874e-05 -5.78723300e-02]

Quadratic coefficients:
[ 2.81214288e-08 -8.23829852e-05  7.62668855e-02]

BACA d = 8
Linear coefficients:
[ 4.46568347e-05 -3.56674443e-02]

Quadratic coefficients:
[-2.88296444e-09  5.79184711e-05 -4.94191847e-02]

BACA d = 16
Linear coefficients:
[ 4.89786085e-05 -5.24271328e-02]

Quadratic coefficients:
[ 1.73658452e-08 -3.09042794e-05  3.04079488e-02]

BACA d = 32
Linear coefficients:
[ 5.41555625e-05 -6.31554865e-02]

Quadratic coefficients:
[ 2.05614453e-08 -4.04270860e-05  3.49226077e-02]

ACA
Linear coefficients:
[ 4.16330694e-06 -4.86718546e-03]

Quadratic coefficients:
[ 3.11179897e-09 -1.01509683e-05  9.97609561e-03]


In [38]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np

# =========================================================
# LOAD DATA
# =========================================================

df = pd.read_csv(
    "frobenius_norms.csv",
    names=["d", "rank", "frob"],
    header=0
)

# =========================================================
# FORCE NUMERIC TYPES
# =========================================================

df["d"] = pd.to_numeric(df["d"])
df["rank"] = pd.to_numeric(df["rank"])
df["frob"] = pd.to_numeric(df["frob"])

# =========================================================
# SORT
# =========================================================

df = df.sort_values(["d", "rank"])

d_values = sorted(df["d"].unique())

# =========================================================
# CREATE FIGURE
# =========================================================

fig = go.Figure()

# =========================================================
# PLOT EACH d
# =========================================================

for d in d_values:

    sub = df[df["d"] == d]

    x = sub["rank"].to_numpy(dtype=float)
    y = sub["frob"].to_numpy(dtype=float)

    # -----------------------------------------------------
    # RAW DATA
    # -----------------------------------------------------

    fig.add_trace(
        go.Scatter(
            x=x,
            y=y,
            mode="lines+markers",
            name=f"d = {d}"
        )
    )

    # -----------------------------------------------------
    # EXPONENTIAL FIT
    # -----------------------------------------------------

    mask = y > 0

    x_fit_data = x[mask]
    y_fit_data = y[mask]

    if len(y_fit_data) > 2:

        logy = np.log(y_fit_data)

        coeff = np.polyfit(
            x_fit_data,
            logy,
            1
        )

        fitted = np.exp(
            coeff[0] * x_fit_data + coeff[1]
        )

        fig.add_trace(
            go.Scatter(
                x=x_fit_data,
                y=fitted,
                mode="lines",
                line=dict(dash="dash"),
                name=f"d = {d} exp fit",
                visible="legendonly"
            )
        )

        print("\n===================================")
        print(f"d = {d}")
        print("===================================")

        print("Exponential decay fit:")
        print(
            f"log(error) = "
            f"{coeff[0]:.6e} * rank + "
            f"{coeff[1]:.6e}"
        )

# =========================================================
# LAYOUT
# =========================================================

fig.update_layout(
    title="Frobenius Error vs Rank",
    xaxis_title="Rank",
    yaxis_title="||A - R||_F²",
    template="plotly_white",
    hovermode="x unified",
    width=1200,
    height=700
)

# =========================================================
# LOG SCALE
# =========================================================

fig.update_yaxes(type="log")

# =========================================================
# SHOW
# =========================================================

fig.show()


d = 1
Exponential decay fit:
log(error) = -2.576116e-02 * rank + 6.102592e+00

d = 2
Exponential decay fit:
log(error) = -3.731992e-02 * rank + 6.083535e+00

d = 4
Exponential decay fit:
log(error) = -4.629335e-02 * rank + 6.292990e+00

d = 8
Exponential decay fit:
log(error) = -5.365627e-02 * rank + 6.637938e+00
